# -------------------------------------------------------------------------
# CONFIGURACIÓN DEL SERVIDOR LOCAL
# -------------------------------------------------------------------------
server.port=8080

# -------------------------------------------------------------------------
# CONFIGURACIÓN DE SEGURIDAD: VALIDACIÓN DE TOKENS DE AZURE AD B2C
# -------------------------------------------------------------------------
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://seguridadbackend2026.b2clogin.com/tfp/82b1437d-d893-4e8d-969e-ebbc42df3a29/B2C_1_auth-flow-v2/v2.0/

# -------------------------------------------------------------------------
# CONFIGURACIÓN DE AWS S3 (Credenciales Completas de AWS Academy / Lab)
# -------------------------------------------------------------------------
spring.cloud.aws.credentials.access-key=TU_AWS_ACCESS_KEY_AQUI
spring.cloud.aws.credentials.secret-key=TU_AWS_SECRET_KEY_AQUI
spring.cloud.aws.credentials.session-token=TU_AWS_SESSION_TOKEN_AQUI
spring.cloud.aws.region.static=us-east-1

# Nombre exacto de tu bucket creado en Amazon S3
aws.s3.bucket-name=storage-api-inscripciones-2026