name: Build and Push Docker Image

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Grant execute permission for mvnw
      run: chmod +x api-inscripciones/mvnw

    - name: Build and Package with Maven
      run: ./api-inscripciones/mvnw -B package --file api-inscripciones/pom.xml -DskipTests

    - name: Verificar si GitHub lee los Secretos (Seguro)
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        echo "Cantidad de caracteres del Usuario: ${#DOCKER_USER}"
        echo "Cantidad de caracteres del Token: ${#DOCKER_PASS}"

    - name: Log in to DockerHub
      shell: bash
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./api-inscripciones
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/api-inscripciones:latest