name: Java CI con Maven y Despliegue

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Descarga el código del repositorio en el contenedor virtual
    - uses: actions/checkout@v4

    # 2. Configura el entorno virtual con Java 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    # 3. Dar permisos de ejecución al script mvnw dentro de la subcarpeta
    # Esto es crítico porque estamos trabajando en una estructura anidada
    - name: Grant execute permission for mvnw
      run: chmod +x api-inscripciones/mvnw

    # 4. Compila el proyecto apuntando específicamente al pom.xml interno
    # Usamos la bandera --file para decirle a Maven exactamente dónde está el archivo de configuración
    - name: Build and Package with Maven
      run: ./api-inscripciones/mvnw -B package --file api-inscripciones/pom.xml -DskipTests