name: Build and Push Docker Image

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Grant execute permission for mvnw
      run: chmod +x api-inscripciones/mvnw

    - name: Build and Package with Maven
      run: ./api-inscripciones/mvnw -B package --file api-inscripciones/pom.xml -DskipTests

    # Pasamos los secretos como variables de entorno seguras para congelar sus caracteres especiales
    - name: Docker Login, Build and Push
      env:
        RAW_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        RAW_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        # 1. Limpiar espacios sin riesgo de romper caracteres especiales
        CLEAN_USER=$(echo "$RAW_USER" | tr -d '[:space:]')
        CLEAN_TOKEN=$(echo "$RAW_TOKEN" | tr -d '[:space:]')
        
        # 2. Autenticación inyectando la variable de entorno segura
        echo "$CLEAN_TOKEN" | docker login -u "$CLEAN_USER" --password-stdin
        
        # 3. Construcción y subida nativa
        docker build -t "$CLEAN_USER/api-inscripciones:latest" ./api-inscripciones
        docker push "$CLEAN_USER/api-inscripciones:latest"